### numpy
> 배열(array)를 다루기 위한 라이브러리

In [ ]:
#install numpy
#pip install numpy

In [1]:
import numpy as np

In [3]:
# np.zeros(n) : 사이즈가 n인 1차원 Null 배열을 만들어라
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# np.ones(n) : 사이즈가 n인 1차원 1 배열을 만들어라
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
# np.arange(n, m) n~(m-1)사이의 값을 가지는 배열을 만들어라
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
# np.eye(n) nXn 사이즈의 matrix를 생성해라
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# 슬라이싱 하는방법
arr = np.eye(4)
a = arr[0:2, 0:2]
print(a)

[[1. 0.]
 [0. 1.]]


In [14]:
# reshape 앞에가 -1 이면 전부라는 뜻
arr = np.arange(1,10)
arr = arr.reshape(-1,1)
print(arr)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [22]:
# N차원 reshape  > 차원이 하나 추가됨
arr = np.array([[[1],[2],[3],[4]]])
arr = arr.reshape(-1,4,1,1)
print(arr.shape)

(1, 4, 1, 1)
